### ISSUE TITLE
PyGRP Export Frame fails since 731412d

### ISSUE THREAD

**Issue by MikaMika** [poiuyqwert/PyMS#157]
Silently when a file already exist and needs overwriting.
Other times it is mentioning AtomicWriter.

> Save Error: Could not save BMP to file

OK:
```
  File "/home/mika/Desktop/pyms/PyMS/Utilities/AtomicWriter.py", line 68, in __del__
    self.discard()
  File "/home/mika/Desktop/pyms/PyMS/Utilities/AtomicWriter.py", line 59, in discard
    if self.handle and not self.handle.closed:
AttributeError: 'AtomicWriter' object has no attribute 'handle'
```

Internal Error:
```
  File "/home/mika/Desktop/pyms/PyMS/FileFormats/BMP.py", line 115, in save_file
    f = AtomicWriter(file,'wb')
  File "/home/mika/Desktop/pyms/PyMS/Utilities/AtomicWriter.py", line 20, in __init__
    self.handle = open(path, mode, encoding=encoding)
                  ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: binary mode doesn't take an encoding argument
```

**Comment by poiuyqwert** [comment]
I've made changes since 731412d and I believe this is already fixed (I was not able to reproduce the issue at least). Can you try with the latest commit and see if its still an issue for you?

**Comment by MikaMika** [comment]
Seems fixed. Thanks!
